PKG_NAME = file
PKG_VERS = 5.11
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = ftp://ftp.astron.com/pub/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = http://www.darwinsys.com/file/
COMMENT  = a file type guesser
LICENSE  = 

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

